### ISSUE TITLE
Side menu of category overlapping with footeer on desktop

### ISSUE THREAD

**Issue by BreakSecurity** [tastyigniter/ti-theme-orange#19]
**Expected behavior:**
Side menu of categories should always be usable... 

**Actual behavior:**
If the list of categories is very long, going down to the bottom of the page from the PC cause overlapping with the footer (in very small screens it happens even without scrolling the page to the bottom).

**Reproduce steps:**
Set up a large number of categories and observe the described behaviour.

**Version:**
v.3.0.4-beta.23.2

**Additional Information:**
![immagine](https://user-images.githubusercontent.com/38836022/98606798-2b59e200-22e8-11eb-8bc9-6186ad7931af.png)

**Suggested fix:**
It would be useful to give the possibility to contract and expand the child categories under the parent categories.

**Comment by BreakSecurity** [comment]
I tried with no success with css

**Comment by babelattke** [comment]
Looks similar to cart issue. There's a fix, please check if it works for this case. 

https://github.com/tastyigniter/TastyIgniter/issues/461

**Comment by sampoyigi** [comment]
@babelattke Can you submit a PR with the fix from tastyigniter/TastyIgniter#461

**Comment by babelattke** [comment]
@sampoyigi I just sent the PR.

**Comment by BreakSecurity** [comment]
Tested, still NOT working as expected. Too many categories I think that the only way would be useful to give the possibility to contract and expand the child categories under the parent categories.

> @babelattke 
> 
> @sampoyigi I just sent the PR.

**Comment by babelattke** [comment]
@BreakSecurity would you mind to share how many categories do you have and how it looks like please?

**Comment by BreakSecurity** [comment]
@babelattke 

In my restaurant there are a large number of categories:
![immagine](https://user-images.githubusercontent.com/38836022/103417194-05371c80-4b8a-11eb-9b44-b16880901ede.png)

As you can see, when I go to the bottom of the page some categories disappear under the footer
![immagine](https://user-images.githubusercontent.com/38836022/103417211-15e79280-4b8a-11eb-8a91-b9a4d5b8552b.png)

One solution could be to make the categories on the left with a drop-down menu, only the ones that have childs categories

**Comment by BreakSecurity** [comment]
@babelattke any news?

**Comment by babelattke** [comment]
@BreakSecurity I tried this:

_One solution could be to make the categories on the left with a drop-down menu, only the ones that have child categories_

But I ended up with no option to filter that parent category. I also added an icon to filter/collapse. Usable on desktop but not on mobile due to its size.

**Comment by asr1436** [comment]
add this css code to custom css in theme advance option. 

.footer {
    position: relative;
}

**Comment by sampoyigi** [comment]
Amazeballs! Thank you @asr1436, I'll add the fix to the core!

**Comment by sampoyigi** [comment]
Ok, that seems to mess up pages with less content. 🤔 

![image](https://user-images.githubusercontent.com/6567634/105580347-bee96d80-5d83-11eb-8806-f3d196786846.png)

**Comment by babelattke** [comment]
@sampoyigi Yes, it does. I've proposed that fix as a temp solution for the menu page. I got some time to work on a better solution that works as expected. 

**/themes/tastyigniter-orange/assets/src/scss/components/_footer.scss**

line 2: 
`position: static;`

**themes/tastyigniter-orange/assets/src/scss/layouts/_layout.scss**

```
body {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  > main {
    padding-top: $page-padding-top;
    flex: 1;
  }
}
```

**Optional:**

**themes/tastyigniter-orange/_partials/footer.blade.php**

Line 1: 
`<div class="footer pt-5 pb-5">`  --->  `<div class="footer py-5">`

_Layouts pages:_

`<footer class="footer pt-5">`  --->  `<footer class="footer">`

**Comment by BreakSecurity** [comment]
It works @babelattke

**Comment by sampoyigi** [comment]
Oops, just seeing your comment @babelattke. I already went with an example from Bootstrap docs.

https://github.com/tastyigniter/ti-theme-orange/commit/4d6c3788cd85600e86a1c69b599770933c54c1df
